import 'package:flutter/material.dart';

//@immutable
class WTWThemeExtension extends ThemeExtension<WTWThemeExtension> {

  WTWThemeExtension({
    this.background1,
    this.background2,
    this.text1,
    this.text2,
    this.text3,
    this.text4,
    this.text5,
    this.primary1,
    this.primary2,
    this.primary3,
    this.primary4,
    this.primary5,
    this.error1,
    this.error2,
    this.error3,
    this.error4,
    this.error5,
    this.success1,
    this.success2,
    this.success3,
    this.success4,
    this.success5,
    this.shade1,
    this.shade2,
    this.shade3,
    this.shade4,
    this.shade5,
  });

  Color? background1, background2,
    text1, text2, text3, text4, text5,
    primary1, primary2, primary3, primary4, primary5,
    error1, error2, error3, error4, error5,
    success1, success2, success3, success4, success5,
    shade1, shade2, shade3, shade4, shade5;

  @override
  ThemeExtension<WTWThemeExtension> copyWith({
    Color? background1,
    Color? background2,
    Color? text1,
    Color? text2,
    Color? text3,
    Color? text4,
    Color? text5,
    Color? primary1,
    Color? primary2,
    Color? primary3,
    Color? primary4,
    Color? primary5,
    Color? error1,
    Color? error2,
    Color? error3,
    Color? error4,
    Color? error5,
    Color? success1,
    Color? success2,
    Color? success3,
    Color? success4,
    Color? success5,
    Color? shade1,
    Color? shade2,
    Color? shade3,
    Color? shade4,
    Color? shade5,
  }) {
    return WTWThemeExtension(
      background1: background1 ?? this.background1,
      background2: background2 ?? this.background2,
      text1: text1 ?? this.text1,
      text2: text2 ?? this.text2,
      text3: text3 ?? this.text3,
      text4: text4 ?? this.text4,
      text5: text5 ?? this.text5,
      primary1: primary1 ?? this.primary1,
      primary2: primary2 ?? this.primary2,
      primary3: primary3 ?? this.primary3,
      primary4: primary4 ?? this.primary4,
      primary5: primary5 ?? this.primary5,
      error1: error1 ?? this.error1,
      error2: error2 ?? this.error2,
      error3: error3 ?? this.error3,
      error4: error4 ?? this.error4,
      error5: error5 ?? this.error5,
      success1: success1 ?? this.success1,
      success2: success2 ?? this.success2,
      success3: success3 ?? this.success3,
      success4: success4 ?? this.success4,
      success5: success5 ?? this.success5,
      shade1: shade1 ?? this.shade1,
      shade2: shade2 ?? this.shade2,
      shade3: shade3 ?? this.shade3,
      shade4: shade4 ?? this.shade4,
      shade5: shade5 ?? this.shade5,
    );
  }

  @override
  ThemeExtension<WTWThemeExtension> lerp(covariant ThemeExtension<WTWThemeExtension>? other, double t) {
    if(other is! WTWThemeExtension) { return this; }

    return WTWThemeExtension(
      background1: Color.lerp(background1, other.background1, t),
      background2: Color.lerp(background2, other.background2, t),
      text1: Color.lerp(text1, other.text1, t),
      text2: Color.lerp(text2, other.text2, t),
      text3: Color.lerp(text3, other.text3, t),
      text4: Color.lerp(text4, other.text4, t),
      text5: Color.lerp(text5, other.text5, t),
      primary1: Color.lerp(primary1, other.primary1, t),
      primary2: Color.lerp(primary2, other.primary2, t),
      primary3: Color.lerp(primary3, other.primary3, t),
      primary4: Color.lerp(primary4, other.primary4, t),
      primary5: Color.lerp(primary5, other.primary5, t),
      error1: Color.lerp(error1, other.error1, t),
      error2: Color.lerp(error2, other.error2, t),
      error3: Color.lerp(error3, other.error3, t),
      error4: Color.lerp(error4, other.error4, t),
      error5: Color.lerp(error5, other.error5, t),
      success1: Color.lerp(success1, other.success1, t),
      success2: Color.lerp(success2, other.success2, t),
      success3: Color.lerp(success3, other.success3, t),
      success4: Color.lerp(success4, other.success4, t),
      success5: Color.lerp(success5, other.success5, t),
      shade1: Color.lerp(shade1, other.shade1, t),
      shade2: Color.lerp(shade2, other.shade2, t),
      shade3: Color.lerp(shade3, other.shade3, t),
      shade4: Color.lerp(shade4, other.shade4, t),
      shade5: Color.lerp(shade5, other.shade5, t),
    );
  }

}