name: wtoolboxweb
description: "Package for creating web applications"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8                # IOS icons lib
  font_awesome_flutter: ^10.7.0          # font_awesome icons libs
  font_awesome_flutter_named: ^1.1.2+1   # font_awesome icons libs
  google_fonts: ^6.2.1                   # fonts
  material_symbols_icons: ^4.2811.0      # material symbols and icons
  icons_launcher: ^3.0.0                 # launcher icon
  flutter_dotenv: ^5.2.1                 # .env library
  get: ^4.6.6                            # getX (state management, translation, themes, mvc...) lib
  http: ^1.3.0                           # http lib
  stomp_dart_client: ^2.1.3              # websockets (stomp) lib
  encrypt: ^5.0.3                        # lib for a set of high-level APIs over PointyCastle for two-way cryptography.
  uuid: ^4.5.1                           # uuid generator
  date_format: ^2.0.9                    # lib for date formatting
  intl: ^0.19.0                          #
  collection: ^1.19.1                    # collections and utilities functions and classes related to collections.
  xml: ^6.5.0                            # xml
  path: ^1.9.1                           # string-based path manipulation lib
  mime: ^2.0.0                           # utilities lib for handling media (MIME) types
  image: ^4.5.2                          # lib which provides server and web apps the ability to load, manipulate, and save images
  share_plus: ^10.1.4                    # email lib
  flutter_svg: ^2.0.17                   # svg lib
  date_picker_plus: ^4.2.0               # datepicker
  signature: ^6.0.0                      #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8

flutter:

  uses-material-design: true

  assets:
    - assets/